version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  bot:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGODB_URI=mongodb://mongo:27017/tg-bot
      - NOWPAYMENTS_API_KEY=${NOWPAYMENTS_API_KEY}
      - NOWPAYMENTS_IPN_SECRET=${NOWPAYMENTS_IPN_SECRET}
      - BASE_URL=http://localhost:3000
    depends_on:
      - mongo
volumes:
  mongo_data:
